import type { InventoryItem, Transaction, PreOrder } from './types';

export const initialInventoryItems: InventoryItem[] = [
  { id: '1', name: 'Amplop ( Merpati 229x110mm )', unit: 'Pcs', quantity: 173 },
  { id: '2', name: 'Amplop Surat', unit: 'Pack', quantity: 458 },
  { id: '3', name: 'Bantex ( 1446-10 70mm Black )', unit: 'Pcs', quantity: 7 },
  { id: '4', name: 'Bantex Folio/Box File', unit: 'Pcs', quantity: 4 },
  { id: '5', name: 'Baterai ( ABC 9 Volt )', unit: 'Pcs', quantity: 16 },
  { id: '6', name: 'Baterai ( ABC A2 )', unit: 'Pcs', quantity: 285 },
  { id: '7', name: 'Baterai ( Alkaline A3 )', unit: 'Pcs', quantity: 12 },
  { id: '8', name: 'Baterai jam ( Maxell 3V )', unit: 'Pcs', quantity: 0 },
  { id: '9', name: 'BIG Folio ( ART.7003 )', unit: 'Pcs', quantity: 2 },
  { id: '10', name: 'Binder Clip ( BIG 32mm )', unit: 'Box', quantity: 55 },
  { id: '11', name: 'Bindex A5', unit: 'Pcs', quantity: 1 },
  { id: '12', name: 'Buku Gelatik Kembar ( Batik )', unit: 'Pcs', quantity: 6 },
  { id: '13', name: 'Buku Tulis ( SIDU )', unit: 'Pack', quantity: 7 },
  { id: '14', name: 'Business File A4', unit: 'Pcs', quantity: 23 },
  { id: '15', name: 'Correction Tape Cair', unit: 'Pcs', quantity: 5 },
  { id: '16', name: 'Correction Tape Kertas', unit: 'Pcs', quantity: 0 },
  { id: '17', name: 'Cutter Besar ( ZRM L-500 )', unit: 'Pcs', quantity: 4 },
  { id: '18', name: 'Cutter Kecil ( KENKO A-300 )', unit: 'Pcs', quantity: 1 },
  { id: '19', name: 'Dispenser Tape', unit: 'Pcs', quantity: 6 },
  { id: '20', name: 'Double Tape 12mm', unit: 'Roll', quantity: 37 },
  { id: '21', name: 'Double Tape Foam ( BEERYTAPE 24mm )', unit: 'Roll', quantity: 8 },
  { id: '22', name: 'Elemen Solder', unit: 'Pcs', quantity: 0 },
  { id: '23', name: 'Gembok', unit: 'Pcs', quantity: 0 },
  { id: '24', name: 'Gunting Besar ( Ideal 8.5" )', unit: 'Pcs', quantity: 2 },
  { id: '25', name: 'Gunting Kecil ( Ideal 4.5" )', unit: 'Pcs', quantity: 0 },
  { id: '26', name: 'ID Card ( BIG )', unit: 'Pcs', quantity: 9 },
  { id: '27', name: 'Isi Cutter Besar ( KENKO L-150 )', unit: 'Pack', quantity: 23 },
  { id: '28', name: 'Isi Cutter Kecil ( KENKO A-100 )', unit: 'Pack', quantity: 129 },
  { id: '29', name: 'Isi Pensil Mekanik ( JOYKO 2B 60mm )', unit: 'Tube', quantity: 8 },
  { id: '30', name: 'Isi Staples Besar ( SDI NO.3 )', unit: 'Box', quantity: 13 },
  { id: '31', name: 'Isi Staples Kecil ( SDI NO.10 )', unit: 'Box', quantity: 26 },
  { id: '32', name: 'Isi Tinta Spidol ( Refill Permanent Marking INK )', unit: 'Bottle', quantity: 5 },
  { id: '33', name: 'Isolasi Kecil ( Nachi 1/2x25 )', unit: 'Roll', quantity: 50 },
  { id: '34', name: 'Isolasi Kertas ( Masking Tape Nachi 24mm )', unit: 'Roll', quantity: 38 },
  { id: '35', name: 'Isolasi Listrik Hitam ( National )', unit: 'Roll', quantity: 9 },
  { id: '36', name: 'Kabel Twist tie ( 100m )', unit: 'Roll', quantity: 1 },
  { id: '37', name: 'Kalkulator ( Citizen CT-555GB )', unit: 'Pcs', quantity: 1 },
  { id: '38', name: 'Kertas A4 (100 GSM)', unit: 'Rim', quantity: 0 },
  { id: '39', name: 'Kertas A4 (70 GSM)', unit: 'Rim', quantity: 8 },
  { id: '40', name: 'Kertas A4 (80 GSM)', unit: 'Rim', quantity: 1 },
  { id: '41', name: 'Kertas Buram F4', unit: 'Rim', quantity: 3 },
  { id: '42', name: 'Kertas F4', unit: 'Rim', quantity: 2 },
  { id: '43', name: 'Kertas Foto', unit: 'Pack', quantity: 1 },
  { id: '44', name: 'Kertas Letter 2 ply', unit: 'Box', quantity: 0 },
  { id: '45', name: 'Kertas Letter 3 Ply', unit: 'Box', quantity: 0 },
  { id: '46', name: 'Kertas Letter 4 Ply', unit: 'Box', quantity: 4 },
  { id: '47', name: 'Kertas Sticker ( E-print A4 135gsm )', unit: 'Pack', quantity: 17 },
  { id: '48', name: 'Lakban Bening Besar ( Faster )', unit: 'Roll', quantity: 0 },
  { id: '49', name: 'Lakban Bening Kecil ( Nachi 12mm )', unit: 'Roll', quantity: 0 },
  { id: '50', name: 'Lem Fox Besar ( 600g )', unit: 'Pcs', quantity: 0 },
  { id: '51', name: 'Lem Fox Kecil ( 70g )', unit: 'Pcs', quantity: 7 },
  { id: '52', name: 'Lem Fox Sedang ( 185g )', unit: 'Pcs', quantity: 0 },
  { id: '53', name: 'Lem Kertas', unit: 'Pcs', quantity: 1 },
  { id: '54', name: 'Lem Power Glue', unit: 'Pcs', quantity: 0 },
  { id: '55', name: 'Map Plastik Tali ( BIG Art.8112 )', unit: 'Pcs', quantity: 11 },
  { id: '56', name: 'Map Plastik Kancing ( BIG Art.8111 )', unit: 'Pcs', quantity: 23 },
  { id: '57', name: 'Mata Solder', unit: 'Pcs', quantity: 2 },
  { id: '58', name: 'Paper Clip ( ZRM NO.3 )', unit: 'Box', quantity: 6 },
  { id: '59', name: 'Paper Clip ( ZRM NO.5 )', unit: 'Box', quantity: 8 },
  { id: '60', name: 'Penggaris Besi ( Butterfly 30cm )', unit: 'Pcs', quantity: 3 },
  { id: '61', name: 'Penghapus Pensil ( BIG )', unit: 'Pcs', quantity: 3 },
  { id: '62', name: 'Pengharum Ruangan', unit: 'Pcs', quantity: 0 },
  { id: '63', name: 'Pensil ( Faber Castell 2B )', unit: 'Box', quantity: 8 },
  { id: '64', name: 'Pines ( COMBO Push Pins )', unit: 'Box', quantity: 29 },
  { id: '65', name: 'Plastik Clip ( 8X12)', unit: 'Pack', quantity: 0 },
  { id: '66', name: 'Plastik Clip ( 16x25 )', unit: 'Pack', quantity: 0 },
  { id: '67', name: 'Plastik Clip ( 30x40 )', unit: 'Pack', quantity: 0 },
  { id: '68', name: 'Plastik Sampah Besar', unit: 'Roll', quantity: 0 },
  { id: '69', name: 'Plastik Sampah Kecil', unit: 'Roll', quantity: 0 },
  { id: '70', name: 'Plastik Sampah Sedang', unit: 'Roll', quantity: 3 },
  { id: '71', name: 'Pulpen Hitam ( Standart AE7 0.5 )', unit: 'Box', quantity: 0 },
  { id: '72', name: 'Pulpen Merah ( Standart AE7 0.5 )', unit: 'Box', quantity: 8 },
  { id: '73', name: 'Pulpen Faster', unit: 'Box', quantity: 0 },
  { id: '74', name: 'Pulpen Gel ( Zhixin-212 )', unit: 'Box', quantity: 16 },
  { id: '75', name: 'Rautan Pencil ( BIG )', unit: 'Pcs', quantity: 2 },
  { id: '76', name: 'Sapu Lantai', unit: 'Pcs', quantity: 0 },
  { id: '77', name: 'Sapu Lindi', unit: 'Pcs', quantity: 0 },
  { id: '78', name: 'Sheet Protector ( BIG Art-5010 F4 )', unit: 'Pack', quantity: 0 },
  { id: '79', name: 'Solasi Fragile', unit: 'Roll', quantity: 14 },
  { id: '80', name: 'Spidol Hitam ( Snowman Marker Permanent Black )', unit: 'Box', quantity: 0 },
  { id: '81', name: 'Spidol Merah ( Snowman Marker Permanent Red )', unit: 'Box', quantity: 10 },
  { id: '82', name: 'Spidol Putih ( Snowman Marker Permanent White )', unit: 'Pcs', quantity: 0 },
  { id: '83', name: 'Stabilo ( KENKO HL-100 )', unit: 'Box', quantity: 6 },
  { id: '84', name: 'Staples Besar ( KENKO HD-50 )', unit: 'Pcs', quantity: 5 },
  { id: '85', name: 'Staples Kecil ( SDI NO.10 )', unit: 'Pcs', quantity: 5 },
  { id: '86', name: 'Sticker Barcode ( 50x20mm )', unit: 'Roll', quantity: 5 },
  { id: '87', name: 'Sticker Bulat Hijau ( T&J No 114 )', unit: 'Sheet', quantity: 1 },
  { id: '88', name: 'Sticker Bulat Hijau ( T&J No 97 )', unit: 'Sheet', quantity: 10 },
  { id: '89', name: 'Sticker Bulat Kuning ( T&J No 97 )', unit: 'Sheet', quantity: 2 },
  { id: '90', name: 'Sticker Bulat Putih ( T&J No 97 )', unit: 'Sheet', quantity: 0 },
  { id: '91', name: 'Sticker Kotak Label Putih ( T&J No 102 )', unit: 'Sheet', quantity: 51 },
  { id: '92', name: 'Sticky Note ( BIG 76x101mm )', unit: 'Pad', quantity: 9 },
  { id: '93', name: 'Tape Cutter ( JOYKO TD-2S )', unit: 'Pcs', quantity: 2 },
  { id: '94', name: 'Tempat Pensil', unit: 'Pcs', quantity: 3 },
  { id: '95', name: 'Tinta Brother BT-5000 (Cyan)', unit: 'Bottle', quantity: 2 },
  { id: '96', name: 'Tinta Brother BT-5000 (Magenta)', unit: 'Bottle', quantity: 2 },
  { id: '97', name: 'Tinta Brother BT-5000 (Yellow)', unit: 'Bottle', quantity: 2 },
  { id: '98', name: 'Tinta Brother BT-D60 (Black)', unit: 'Bottle', quantity: 2 },
  { id: '99', name: 'Tinta Epson 003 (Black)', unit: 'Bottle', quantity: 2 },
  { id: '100', name: 'Tinta Epson 003 (Cyan)', unit: 'Bottle', quantity: 3 },
  { id: '101', name: 'Tinta Epson 003 (Magenta)', unit: 'Bottle', quantity: 2 },
  { id: '102', name: 'Tinta Epson 003 (Yellow)', unit: 'Bottle', quantity: 2 },
  { id: '103', name: 'Tinta Epson 664 (Black)', unit: 'Bottle', quantity: 1 },
  { id: '104', name: 'Tinta Epson 664 (Cyan)', unit: 'Bottle', quantity: 1 },
  { id: '105', name: 'Tinta Epson 664 (Magenta)', unit: 'Bottle', quantity: 1 },
  { id: '106', name: 'Tinta Epson 664 (Yellow)', unit: 'Bottle', quantity: 1 },
  { id: '107', name: 'Tinta Epson Lx 310', unit: 'Cartridge', quantity: 3 },
  { id: '108', name: 'Tinta Ribbon ( 110x300m )', unit: 'Roll', quantity: 0 },
  { id: '109', name: 'Tissu', unit: 'Pack', quantity: 13 },
  { id: '110', name: 'Tissue Toilet ( Nice )', unit: 'Roll', quantity: 18 },
  { id: '111', name: 'WD-40 (120 mL)', unit: 'Can', quantity: 1 },
  { id: '112', name: 'WD-40 (191 mL)', unit: 'Can', quantity: 0 },
  { id: '113', name: 'Kertas Print 3ply ( 9\'5"x11")', unit: 'Box', quantity: 2 },
  { id: '114', name: 'Kertas Print 4ply ( 9\'5"x11")', unit: 'Box', quantity: 0 },
  { id: '115', name: 'Busa cuci piring', unit: 'Pcs', quantity: 0 },
];

export const transactions: Transaction[] = [];

export const preOrders: PreOrder[] = [];
